[package]
name = "sf-dataset"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.9.0"
tokio = { version = "1.40.0", features = ["full"] }
lbase2 = { path = "/home/alexander-mt/Development/lbase2" }
serde = { version = "1.0.217", features = ["derive"] }
